language: android
jdk: oraclejdk8
sudo: required
before_cache: "-rm -f $HOME/.gradle/caches/modules-2/modules-2.lock -rm -fr $HOME/.gradle/caches/*/plugin-resolution/"
cache:
  directories: "-$HOME/.gradle/caches/ -$HOME/.gradle/wrapper/ -$HOME/.android/build-cache"
env:
  global:
  - ANDROID_API=28
  - ANDROID_EMULATOR_LEVEL=18
  - ANDROID_BUILD_TOOLS_VERSION=28.0.1
  - ADB_INSTALL_TIMEOUT=5
  - ANDROID_ABI=armeabi-v7a
  - ANDROID_TAG=google_apis
  - QEMU_AUDIO_DRV=none
android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API_LEVEL
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
script:
- android list targets
before_install:
- openssl aes-256-cbc -K $encrypted_12e97ba04df2_key -iv $encrypted_12e97ba04df2_iv
  -in android.jks.enc -out android.jks -d

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: UjYmSLc7XYC13ckag7JcyP2qresvZn6j3YUjlZ+93KgMj14MDP+BcWV8ngsGR5FKHinkuVeMIVTWRaky5uOiVfAQeVjHNYT6cImo1iLzHxH3fx22Rc8xe/MCjtFePL8X2gYdxE7NVNbYIMReMCZFfM1s3KIBZmehI80PObjB0G2PeRIlVclcI0YWw7Qvgmi1b6+lZF6PkwuZvAMzGB+jqcs338GhM/wwbWh07uzZJCUT//edBWw7MX8bZEKmnLCGtgcdwwUQ4b5Zz2MA8WfDp2Aua5BGekxUc/TlEakdn9KGEIsRjiSEFFJaXuLsDXfi3rDh2nYHyE86Vw91RwIOC3C0UOBfgz5nv27JavlOEYfXaf8PV1YqwYYSMYO1JTBL3H7nxN5JhZXsvLjUyCVzuD+2CsEA6hItihBxLsBSG5ZjFaxSgzXKu+P6JMpWFHT3YyADqBeBTkUgEueSnoeyi8g50W1sI3r3Q0X1dZrRmhOy+OFFRRCMcf/qPZ/MARQCiCubL0Pnh+OUFskdmE0tmyyx8kPaqeunzNbUkyUigvEWCyfSUnIMKLQuzqf+6cO4g0i+OXTuKMAKONBveS4NNBSvrwGjPHNoft6lmKij+2m2tGzUFQDYoYiLMatFRV/j1HxGIk8z3ksQTxaqsghl7g3qhGrwwEwnN6hbFdVNOaw=
  file_glob: true
  file: "../app/release/*"
  on:
    repo: vladbbb/mathApp
    tags: true
